// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgOX64zKKf_amqIEjPUapntpoyZZbG50I',
    appId: '1:1056081118484:web:567754a286dabe5750ee01',
    messagingSenderId: '1056081118484',
    projectId: 'wazzifni-project',
    authDomain: 'wazzifni-project.firebaseapp.com',
    storageBucket: 'wazzifni-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxQuRKivjK6ujHc-nHomKOCYePG0JqslA',
    appId: '1:1056081118484:android:37da361eb61f16f650ee01',
    messagingSenderId: '1056081118484',
    projectId: 'wazzifni-project',
    storageBucket: 'wazzifni-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVPPixfbueTrIbcT-6fwbMymlLbB-TYEo',
    appId: '1:1056081118484:ios:4f11e48bcf8db27650ee01',
    messagingSenderId: '1056081118484',
    projectId: 'wazzifni-project',
    storageBucket: 'wazzifni-project.firebasestorage.app',
    iosBundleId: 'com.wazzifni.admin.wazzifniAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVPPixfbueTrIbcT-6fwbMymlLbB-TYEo',
    appId: '1:1056081118484:ios:4f11e48bcf8db27650ee01',
    messagingSenderId: '1056081118484',
    projectId: 'wazzifni-project',
    storageBucket: 'wazzifni-project.firebasestorage.app',
    iosBundleId: 'com.wazzifni.admin.wazzifniAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgOX64zKKf_amqIEjPUapntpoyZZbG50I',
    appId: '1:1056081118484:web:8437e73fb004246450ee01',
    messagingSenderId: '1056081118484',
    projectId: 'wazzifni-project',
    authDomain: 'wazzifni-project.firebaseapp.com',
    storageBucket: 'wazzifni-project.firebasestorage.app',
  );
}
